captainVersion: 4
services:
    $$cap_appname-db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_mysql_root_password
            MYSQL_DATABASE: $$cap_mysql_db
            MYSQL_USER: $$cap_mysql_user
            MYSQL_PASSWORD: $$cap_mysql_password
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        caproverExtra:
            notExposeAsWebApp: true
    $$cap_appname:
        image: wordpress:latest
        restart: always
        depends_on:
            - $$cap_appname-db
        environment:
            WORDPRESS_DB_HOST: srv-captain--$$cap_appname-db
            WORDPRESS_DB_USER: $$cap_mysql_user
            WORDPRESS_DB_PASSWORD: $$cap_mysql_password
            WORDPRESS_DB_NAME: $$cap_mysql_db
        volumes:
            - $$cap_appname-wp-content:/var/www/html/wp-content
        caproverExtra:
            containerHttpPort: 80
caproverOneClickApp:
    variables:
        - id: $$cap_mysql_root_password
          label: MySQL Root Password
          defaultValue: $$cap_gen_random_hex(16)
        - id: $$cap_mysql_user
          label: WordPress DB User
          defaultValue: wordpress
        - id: $$cap_mysql_password
          label: WordPress DB Password
          defaultValue: $$cap_gen_random_hex(12)
        - id: $$cap_mysql_db
          label: WordPress Database Name
          defaultValue: wordpress
    instructions:
        start: WordPress installation starting
        end: WordPress ready at http://$$cap_appname.$$cap_root_domain
    displayName: WordPress Simple
    description: Simple WordPress with MySQL
