captainVersion: 4
services:
    $$cap_appname-db:
        image: mysql:$$cap_mysql_version
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_mysql_root_password
            MYSQL_DATABASE: $$cap_mysql_db
            MYSQL_USER: $$cap_mysql_user
            MYSQL_PASSWORD: $$cap_mysql_password
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        image: themirage80/wordpress-client-optimized:latest
        restart: always
        depends_on:
            - $$cap_appname-db
        environment:
            WORDPRESS_DB_HOST: srv-captain--$$cap_appname-db
            WORDPRESS_DB_USER: $$cap_mysql_user
            WORDPRESS_DB_PASSWORD: $$cap_mysql_password
            WORDPRESS_DB_NAME: $$cap_mysql_db
            WORDPRESS_TABLE_PREFIX: $$cap_wp_table_prefix
        volumes:
            - $$cap_appname-wp-content:/var/www/html/wp-content
        caproverExtra:
            containerHttpPort: '80'
caproverOneClickApp:
    variables:
        - id: $$cap_mysql_version
          label: MySQL Version
          defaultValue: '8.0'
        - id: $$cap_mysql_root_password
          label: MySQL Root Password
          defaultValue: $$cap_gen_random_hex(20)
        - id: $$cap_mysql_user
          label: MySQL User
          defaultValue: wordpress
        - id: $$cap_mysql_password
          label: MySQL Password
          defaultValue: $$cap_gen_random_hex(16)
        - id: $$cap_mysql_db
          label: MySQL Database Name
          defaultValue: wordpress
        - id: $$cap_wp_table_prefix
          label: WordPress Table Prefix
          defaultValue: wp_
    instructions:
        start: WordPress Clienti Ottimizzato in installazione. Upload fino a 128MB incluso.
        end: WordPress pronto! Vai su http://$$cap_appname.$$cap_root_domain per completare setup.
    displayName: WordPress Clienti (Ottimizzato)
    isOfficial: false
    description: WordPress ottimizzato per clienti con upload 128MB e plugin essenziali preinstallati.
